Урок 3
Матрицы и матричные операции. Часть 1

1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

a) произведение не определено тк размерности матриц не подходящие (количество столбцов первой должно быть равно количеству строк второй)

б) Определено, размерность итоговой будет 2х3

в) Определено, размерность итоговой будет 8х8

г) Квадратные, одинаковой размерности точно перемножаются итоговая имеет такую-же размерность.

2. Найти сумму и произведение матриц 

$A = 
\begin{pmatrix}
1 & -2 \\
3 & 0 
\end{pmatrix}
$

$B = 
\begin{pmatrix}
4 & -1 \\
0 & 5 
\end{pmatrix}
$

In [7]:
# Сумма
import numpy as np
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
s = np.array([[a[0][0] + b[0][0], a[0][1] + b[0][1]], [a[1][0] + b[1][0], a[1][1] + b[1][1]]])
s

array([[ 5, -3],
       [ 3,  5]])

In [9]:
# Ну или используя собственно numpy
a+b

array([[ 5, -3],
       [ 3,  5]])

In [16]:
# Произведение:
np.array([[a[0][0] * b[0][0] + a[0][1] * b[1][0], a[0][0] * b[0][1] + a[0][1] * b[1][1]],
           [a[1][0] * b[0][0] + a[1][1] * b[1][0], a[1][0] * b[0][1] + a[1][1] * b[1][1]]])

array([[  4, -11],
       [ 12,  -3]])

In [17]:
# Через numpy.dot
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. 

Вычислить линейную комбинацию $3A - 2B + 4C$  для матриц  

$A = 
\begin{pmatrix}
1 & 7 \\
3 & -6 
\end{pmatrix}
B = 
\begin{pmatrix}
0 & 5 \\
2 & -1 
\end{pmatrix}
C = 
\begin{pmatrix}
2 & -4 \\
1 & 1 
\end{pmatrix}
$

In [20]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

# Честно говоря лень все это писать много раз - сделаю функции
def m2_sum(x, y):
    return np.array([[x[0][0] + y[0][0], x[0][1] + y[0][1]], [x[1][0] + y[1][0], x[1][1] + y[1][1]]])

def m2_scalar_mult(x, s):
    return np.array([[x[0][0] * s, x[0][1] * s], [x[1][0] * s, x[1][1] * s]])

# Тогда заданная линейная комбинация будет:
m2_sum(m2_sum(m2_scalar_mult(a, 3), -m2_scalar_mult(b, 2)), m2_scalar_mult(c, 4))

array([[ 11,  -5],
       [  9, -12]])

In [22]:
# Проверим в numpy:
3 * a - 2 * b + 4 * c

array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица  

$A = 
\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}
$

Вычислить  $A\cdot A^T$ и $A^T \cdot A$

In [25]:
a = np.array([[4, 1], [5, -2], [2, 3]])
a_t = np.array([[4, 5, 2], [1, -2, 3]])

In [58]:
# Два перемножения - лучше сразу функцию сделать

def m_mult(x, y):
    product = np.zeros(shape=(x.shape[0],y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            for k in range(x.shape[1]):
                product[i][j] += x[i][k] * y[k][j]
    return product

In [59]:
m_mult(a, a_t)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [60]:
# Теперь в обратном порядке
m_mult(a_t, a)

array([[45.,  0.],
       [ 0., 14.]])

In [61]:
# Проверим
np.dot(a, a_t)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [62]:
np

array([[45,  0],
       [ 0, 14]])

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

А.. эмм.. уже сделал в задании выше ) не то, что-бы совсем не используя numpy, но думаю такой вариант использования допустим в этом задании.. 